name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q
